local P,R,C,U=game:GetService("Players"),game:GetService("RunService"),game:GetService("CoreGui"),game:GetService("UserInputService")
local lP,esp,gunEsp,conn=P.LocalPlayer,false,false,nil
local function rem(ch) local r=ch:FindFirstChild("HumanoidRootPart") if r then local old=r:FindFirstChild("BoxHighlight") if old then old:Destroy() end end end
local function apply(p) if not esp or p==lP then return end local ch=p.Character if ch then local r=ch:FindFirstChild("HumanoidRootPart") if r then local col=Color3.fromRGB(0,255,0) local bp=p:FindFirstChild("Backpack") if ch:FindFirstChild("Knife") or (bp and bp:FindFirstChild("Knife")) then col=Color3.fromRGB(255,0,0) elseif ch:FindFirstChild("Gun") or (bp and bp:FindFirstChild("Gun")) then col=Color3.fromRGB(0,0,255) end local cur=ch:FindFirstChild("PlayerChams") if not cur or cur.FillColor~=col then if cur then cur:Destroy() end local h=Instance.new("Highlight") h.Name="PlayerChams" h.FillColor=col h.FillTransparency=0.75 h.OutlineColor=col h.OutlineTransparency=0.2 h.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop h.Parent=ch end end end end
local function toggEsp(st) esp=st if esp then conn=R.Heartbeat:Connect(function() for _,p in pairs(P:GetPlayers()) do pcall(apply,p) end end) else if conn then conn:Disconnect() end for _,p in pairs(P:GetPlayers()) do if p.Character then rem(p.Character) local h=p.Character:FindFirstChild("PlayerChams") if h then h:Destroy() end end end end end
task.spawn(function() while true do task.wait(0.5) local g=workspace:FindFirstChild("GunDrop",true) if gunEsp and g then if not g:FindFirstChild("GunHighlight") then local h=Instance.new("Highlight") h.Name="GunHighlight" h.FillColor=Color3.fromRGB(255,0,255) h.FillTransparency=0.3 h.OutlineColor=Color3.fromRGB(255,255,255) h.OutlineTransparency=0 h.DepthMode=Enum.HighlightDepthMode.AlwaysOnTop h.Parent=g end elseif not gunEsp and g then local h=g:FindFirstChild("GunHighlight") if h then h:Destroy() end end end end)
if C:FindFirstChild("HerdwavysHubGui") then C.HerdwavysHubGui:Destroy() end
local Gui=Instance.new("ScreenGui",C) Gui.Name="HerdwavysHubGui"
local MF=Instance.new("Frame",Gui) MF.Size=UDim2.new(0,600,0,400) MF.Position=UDim2.new(0.5,-300,0.5,-200) MF.BackgroundColor3=Color3.fromRGB(12,12,14) MF.BorderSizePixel=0 MF.Active=true MF.Draggable=true
Instance.new("UICorner",MF).CornerRadius=UDim.new(0,14)
local str=Instance.new("UIStroke",MF) str.Color=Color3.fromRGB(255,30,30) str.Thickness=2
local TB=Instance.new("Frame",MF) TB.Size=UDim2.new(1,0,0,35) TB.BackgroundTransparency=1
local LT=Instance.new("TextLabel",TB) LT.Size=UDim2.new(0,160,1,0) LT.Position=UDim2.new(0,15,0,0) LT.BackgroundTransparency=1 LT.Text="Herdwavy's Hub" LT.TextColor3=Color3.fromRGB(255,255,255) LT.Font=Enum.Font.GothamBold LT.TextSize=15 LT.TextXAlignment=Enum.TextXAlignment.Left
local Cl=Instance.new("TextButton",TB) Cl.Size=UDim2.new(0,30,0,30) Cl.Position=UDim2.new(1,-40,0,3) Cl.BackgroundTransparency=1 Cl.Text="✕" Cl.TextColor3=Color3.fromRGB(150,150,150) Cl.Font=Enum.Font.GothamBold Cl.TextSize=14 Cl.MouseButton1Click:Connect(function() Gui:Destroy() end)
local Mn=Instance.new("TextButton",TB) Mn.Size=UDim2.new(0,30,0,30) Mn.Position=UDim2.new(1,-75,0,3) Mn.BackgroundTransparency=1 Mn.Text="—" Mn.TextColor3=Color3.fromRGB(150,150,150) Mn.Font=Enum.Font.GothamBold Mn.TextSize=14
local SP=Instance.new("Frame",MF) SP.Size=UDim2.new(0,150,1,-35) SP.Position=UDim2.new(0,0,0,35) SP.BackgroundColor3=Color3.fromRGB(18,18,22) SP.BorderSizePixel=0
Instance.new("UICorner",SP).CornerRadius=UDim.new(0,14)
local function cTab(n,y,a) local f=Instance.new("Frame",SP) f.Size=UDim2.new(0,130,0,35) f.Position=UDim2.new(0,10,0,y) f.BorderSizePixel=0 local t=Instance.new("TextLabel",f) t.Size=UDim2.new(1,0,1,0) t.BackgroundTransparency=1 t.Text=n t.Font=Enum.Font.GothamBold t.TextSize=13 if a then f.BackgroundColor3=Color3.fromRGB(35,15,15) t.TextColor3=Color3.fromRGB(255,50,50) Instance.new("UIStroke",f).Color=Color3.fromRGB(255,30,30) else f.BackgroundTransparency=1 t.TextColor3=Color3.fromRGB(130,130,140) end end
cTab("Information",15,false) cTab("Main",60,false) cTab("Visuals",105,true)
local Cont=Instance.new("Frame",MF) Cont.Size=UDim2.new(1,-175,1,-55) Cont.Position=UDim2.new(0,165,0,45) Cont.BackgroundTransparency=1
local function cTog(n,y,cb) local f=Instance.new("Frame",Cont) f.Size=UDim2.new(1,0,0,50) f.Position=UDim2.new(0,0,0,y) f.BackgroundColor3=Color3.fromRGB(22,22,26) f.BorderSizePixel=0 Instance.new("UICorner",f).CornerRadius=UDim.new(0,8) local l=Instance.new("TextLabel",f) l.Size=UDim2.new(0,250,1,0) l.Position=UDim2.new(0,15,0,0) l.BackgroundTransparency=1 l.Text=n l.TextColor3=Color3.fromRGB(230,230,235) l.Font=Enum.Font.GothamMedium l.TextSize=13 l.TextXAlignment=Enum.TextXAlignment.Left local b=Instance.new("TextButton",f) b.Size=UDim2.new(0,45,0,24) b.Position=UDim2.new(1,-60,0.5,-12) b.BackgroundColor3=Color3.fromRGB(45,45,50) b.Text="" local c=Instance.new("Frame",b) c.Size=Vector2.new(18,18) c.Position=UDim2.new(0,3,0.5,-9) c.BackgroundColor3=Color3.fromRGB(255,255,255) Instance.new("UICorner",b).CornerRadius=UDim.new(1,0) Instance.new("UICorner",c).CornerRadius=UDim.new(1,0) local act=false b.MouseButton1Click:Connect(function() act=not act cb(act) if act then b.BackgroundColor3=Color3.fromRGB(255,30,30) c:TweenPosition(UDim2.new(1,-21,0.5,-9),0,0,0.15) else b.BackgroundColor3=Color3.fromRGB(45,45,50) c:TweenPosition(UDim2.new(0,3,0.5,-9),0,0,0.15) end end) end
cTog("Player ESP (Chams)",0,function(s) toggEsp(s) end) cTog("Dropped Gun ESP",60,function(s) gunEsp=s end)
local RB=Instance.new("TextButton",MF) RB.Size=UDim2.new(0,20,0,20) RB.Position=UDim2.new(1,-20,1,-20) RB.BackgroundTransparency=1 RB.Text="◢" RB.TextColor3=Color3.fromRGB(80,80,85) RB.Font=Enum.Font.GothamBold RB.TextSize=14 local res,sSz,sPs=false,nil,nil
RB.InputBegan:Connect(function(i) if i.UserInputType==Enum.UserInputType.MouseButton1 then res=true sSz=MF.Size sPs=i.Position end end)
U.InputChanged:Connect(function(i) if res and i.UserInputType==Enum.UserInputType.MouseMovement then local d=i.Position-sPs MF.Size=UDim2.new(0,math.clamp(sSz.X.Offset+d.X,400,900),0,math.clamp(sSz.Y.Offset+d.Y,300,600)) end end)
U.InputEnded:Connect(function(i) if i.UserInputType==Enum.UserInputType.MouseButton1 then res=false end end)
local Tgl=Instance.new("TextButton",Gui) Tgl.Size=UDim2.new(0,45,0,45) Tgl.Position=UDim2.new(0,15,0,15) Tgl.BackgroundColor3=Color3.fromRGB(15,15,18) Tgl.Text="H" Tgl.TextColor3=Color3.fromRGB(255,30,30) Tgl.Font=Enum.Font.GothamBold Tgl.TextSize=22 local tSt=Instance.new("UIStroke",Tgl) tSt.Color=Color3.fromRGB(255,30,30) tSt.Thickness=2 Instance.new("UICorner",Tgl).CornerRadius=UDim.new(1,0)
local function tVis() MF.Visible=not MF.Visible if MF.Visible then Tgl.TextColor3=Color3.fromRGB(255,30,30) tSt.Color=Color3.fromRGB(255,30,30) else Tgl.TextColor3=Color3.fromRGB(120,120,120) tSt.Color=Color3.fromRGB(50,50,50) end end
Tgl.MouseButton1Click:Connect(tVis) Mn.MouseButton1Click:Connect(tVis)
